### ISSUE TITLE
[Bug]: hcloud provider error on hcloud_load_balancer_network.cluster creation after upgrade to v2.17.1

### ISSUE THREAD

**Issue by jr-dimedis** [kube-hetzner/terraform-hcloud-kube-hetzner#1736]
### Description

I upgraded the kube-hetzner module from v2.17.0 to v2.17.1 and `terraform apply` results in this error:

```
Terraform will perform the following actions:

  # module.kube-hetzner.hcloud_load_balancer_network.cluster[0] will be created
  + resource "hcloud_load_balancer_network" "cluster" {
      + enable_public_interface = true
      + id                      = (known after apply)
      + ip                      = (known after apply)
      + load_balancer_id        = 1659641
      + subnet_id               = "2919908-10.0.0.0/16"
    }

  # module.kube-hetzner.hcloud_load_balancer_target.cluster[0] will be created
  + resource "hcloud_load_balancer_target" "cluster" {
      + id               = (known after apply)
      + label_selector   = "cluster=k8stest1,engine=k3s,provisioner=terraform,role=agent_node"
      + load_balancer_id = 1659641
      + type             = "label_selector"
      + use_private_ip   = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.kube-hetzner.hcloud_load_balancer_network.cluster[0]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.kube-hetzner.hcloud_load_balancer_network.cluster[0], provider "provider[\"registry.terraform.io/hetznercloud/hcloud\"]" produced an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

The load balancer id in the output corresponds to the nginx load balancer I configured with kube-hetzner (and not the control plane load balancer I activated as well).

Maybe this report should go to `hetznercloud/hcloud` but I thought it's worth to report this here and getting some help! Otherwise just tell me and I'll create an issue in the `hcloud` project.

Thanks!

### Kube.tf file

```terraform
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
  ingress_controller = "nginx"
  use_control_plane_lb = true
```

### Used provider versions

```
Providers required by configuration:
.
├── provider[registry.terraform.io/hetznercloud/hcloud] >= 1.49.1
├── provider[registry.terraform.io/hashicorp/vault]
└── module.kube-hetzner
    ├── provider[registry.terraform.io/hashicorp/local] >= 2.5.2
    ├── provider[registry.terraform.io/tenstad/remote] >= 0.1.3
    ├── provider[registry.terraform.io/integrations/github] >= 6.4.0
    ├── provider[registry.terraform.io/hashicorp/null]
    ├── provider[registry.terraform.io/hashicorp/random]
    ├── provider[registry.terraform.io/hashicorp/cloudinit]
    ├── provider[registry.terraform.io/hetznercloud/hcloud] >= 1.49.1
    ├── module.agents
    │   ├── provider[registry.terraform.io/hetznercloud/hcloud] >= 1.49.1
    │   ├── provider[registry.terraform.io/hashicorp/null]
    │   ├── provider[registry.terraform.io/hashicorp/random]
    │   └── provider[registry.terraform.io/hashicorp/cloudinit]
    └── module.control_planes
        ├── provider[registry.terraform.io/hetznercloud/hcloud] >= 1.49.1
        ├── provider[registry.terraform.io/hashicorp/null]
        ├── provider[registry.terraform.io/hashicorp/random]
        └── provider[registry.terraform.io/hashicorp/cloudinit]
```

### Platform

Linux

**Comment by jr-dimedis** [comment]
I just upgraded hetznercloud/hcloud to latest version 1.50.1 - same error.

**Comment by jr-dimedis** [comment]
I think I found an interesting issue in the hcloud issue tracker which is related to this bug here:

https://github.com/hetznercloud/terraform-provider-hcloud/issues/289

Having more than one network attached to a load balancer is not supported by Hetzner.

Obviously kube-hetzner does not recognize that there is a private network already and tries to create another one.

How can I prevent that?

**Comment by sd-f** [comment]
Same error here.

I set LOG to INFO and found:

```
2025-05-20T11:53:42.402+0200 [WARN]  Provider "registry.terraform.io/hetznercloud/hcloud" produced an invalid plan for module.kube-hetzner.hcloud_load_balancer_network.cluster[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .enable_public_interface: planned value cty.True for a non-computed  attribute
```

Don't know if it has something to do with that.

Also the label `role=agent_node` is missing in the existing load_balancer. This might lead to the additional creation.

Any help would be appreciated.

**Comment by jr-dimedis** [comment]
This is a new terraform resource, which is now created explicitly and before somehow automatically, it looks like.

I think a solution could be to import the existing network manually into the Terraform state (which then would be worth to be mentioned in the release notes for upgraders, if that's the only solution).

But I'm not sure about the `hcloud_load_balancer_target` resource: up to now all servers were individually added as targets to the load balancer (how?), now this should be accomplished with a label selector. Maybe it's necessary to attach all required labels manually as well...

**Comment by jr-dimedis** [comment]
I just imported the resource and it was not really "straight forward"...

I did the following:

```bash
# Get load balancer id
hcloud load-balancer describe $CLUSTER_NAME-nginx --output json | jq .id

# Get the network id
hcloud network describe $CLUSTER_NAME --output json | jq .id

# Perform import
terraform import module.kube-hetzner.hcloud_load_balancer_network.cluster[0] "$LB_ID-$NETWORK_ID"
```

But `terraform plan` showed that the resource needs to be replaced.

```
  # module.kube-hetzner.hcloud_load_balancer_network.cluster[0] must be replaced
-/+ resource "hcloud_load_balancer_network" "cluster" {
      ~ id                      = "1659641-2919908" -> (known after apply)
      ~ ip                      = "10.254.0.3" -> (known after apply)
      - network_id              = 2919908 -> null # forces replacement
      + subnet_id               = "2919908-10.0.0.0/16" # forces replacement
        # (2 unchanged attributes hidden)
    }
```

Since I didn't know if that can affect the cluster, I manually edited the state JSON.

```bash
# Pull state to JSON file
terraform state pull > state.json
```

I increased serial, removed network_id and added subnet_id like so:

```diff
-            "network_id": 2919908,
-            "subnet_id": null
+            "network_id": null,
+            "subnet_id": "2919908-10.0.0.0/16"
```

```bash
# Push edited state back
terraform state push state.jeon
```

Now `terraform plan` showed that only the "target" resource has to be added. I did that and it worked.

But now I see this label based target in the Cloud Console - without any targets (although all servers have the required labels). Maybe because all nodes are assigned directly already.

![Image](https://github.com/user-attachments/assets/15244e15-856e-47eb-9294-10a5e0a47e0d)

So now everything works "more or less", but the situation isn't really satisfying. I did all that on a test cluster and I am not sure if I like to do the same on production clusters.

So still any help is appreciated, if there is a better solution.

**Comment by jr-dimedis** [comment]
I just manually removed the server targets one by one from the "Cloud Server" target group in the Cloud Console and they popped up one by one in the label target group.

At the end the "Cloud Server" target group disappeared completely.

`terraform plan` didn't detect any drift, so anything is clean now.

I think the Hetzner CCM was responsible for the "Cluster Server" target group. Maybe because in v2.17.0 this wasn't created by Terraform, CCM created it implicitly for convenience.

I am still not sure that the most efficient way to handle this v2.17.0 -> v2.17.1 upgrade situation is. Maybe the manual state editing I performed is not necessary and we could let Terraform recreate the load balancer network. But now I can't test this anymore.

**Comment by pschiffe** [comment]
Source of this issue:
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1567/files#diff-1366caed88e51e22bcd5a911420820bee3495d781ecccd85f25e00170fc325b8R22

@xavierleune what's the proper way to upgrade?

**Comment by BrammyS** [comment]
Experiencing the same issue. I am unable to upgrade from 2.17.0

**Comment by jr-dimedis** [comment]
I can add that when applying 2.17.1 all `[...].hcloud_server.server` resources are changed in-place which triggers an instant server reboot. For the whole cluster and without any draining. Of course, a real test of resilience, but I think undesirable in most cases.

It would be good if we had a documented way of carrying out the update without restarting all servers, or at least in a controlled manner.

**Comment by xavierleune** [comment]
thanks for all the details, I'll try to look into it in the coming days ; perhaps next week.
I'll try to figure out how to perform this upgrade smoothly, if you have any idea feel free to share ^^

**Comment by mysticaltech** [comment]
Folks, I did not test that PR yet, but there's a good chance that it's the fix. If you can test, please let me know.

**Comment by mmack** [comment]
Same problem. Watching.

**Comment by mysticaltech** [comment]
Ok, thanks for the feedback folks. Will have a look tonight.

**Comment by arbianshkodra** [comment]
@mysticaltech I created a new PR, was not sure if I could contribute to the existing one which you had. This fixed these issues for me. Let me know if it works you and others.

**Comment by mysticaltech** [comment]
Thanks @arbianshkodra , appreciate it very much, will review later tonight 🙏

**Comment by djxy** [comment]
For those having the issue, just set the module version to `version = "2.17.0"` for the moment. It fixed the issue for me.

**Comment by ryshoooo** [comment]
Hey folks, sorry to keep this still up, but after upgrading to 2.17.3, I am getting a different error after terraform apply:

```
Terraform will perform the following actions:

  # module.kube-hetzner.hcloud_load_balancer_network.cluster[0] will be created
  + resource "hcloud_load_balancer_network" "cluster" {
      + enable_public_interface = true
      + id                      = (known after apply)
      + ip                      = (known after apply)
      + load_balancer_id        = 2414430
      + subnet_id               = "10817146-10.0.0.0/16"
    }

  # module.kube-hetzner.hcloud_load_balancer_target.cluster[0] will be created
  + resource "hcloud_load_balancer_target" "cluster" {
      + id               = (known after apply)
      + label_selector   = "cluster=k3s,engine=k3s,provisioner=terraform,role in (control_plane_node,agent_node)"
      + load_balancer_id = 2414430
      + type             = "label_selector"
      + use_private_ip   = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.kube-hetzner.hcloud_load_balancer_network.cluster[0]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.kube-hetzner.hcloud_load_balancer_network.cluster[0], provider
│ "provider[\"registry.terraform.io/hetznercloud/hcloud\"]" produced an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

do I need to change something in my tf apply file, or is there still a bug?

**Comment by arbianshkodra** [comment]
@ryshoooo if you tried to manually attach load balancer when stuck, try to use hcloud to detach from network and run tofu apply again. That should do it.

**Comment by arbianshkodra** [comment]
@mysticaltech something strange is happening. On the lower version 2.17, the Load Balancer is targeting (Autoscaling, Agent nodes) in my case there are 2. In this new version Load Balancer is targeting all servers apart from Autoscaling nodes. Is there something wrong with labels?

**Comment by ryshoooo** [comment]
> [@ryshoooo](https://github.com/ryshoooo) if you tried to manually attach load balancer when stuck, try to use hcloud to detach from network and run tofu apply again. That should do it.

thanks @arbianshkodra, but I didn't do anything manual. Only via terraform, tried to upgrade to 2.17.2, which had the error described in this issue. After that I tried running 2.17.3, which yields this error, none clickops were performed. I did also `terraform refresh` and `terraform apply`, didn't help, the same error. I don't really want to start manually messing around in hcloud to diverge the state even more. I also don't want to detach the LB right now, as we have clients depending on the services running in the cluster, I can try to do that during night hours.

**Comment by arbianshkodra** [comment]
@ryshoooo try to do that during night hours. Also if you have any autoscaling nodes, try to delete them as well because Load Balancer is not detecting the existing ones. This should fix it

**Comment by mysticaltech** [comment]
@ryshoooo Please gimme the full logs in a new issue.

**Comment by sd-f** [comment]
Maybe more interresting (the part before)

```
2025-06-10T13:31:49.671+0200 [INFO]  Starting apply for module.kube-hetzner.hcloud_load_balancer_network.cluster[0]
2025-06-10T13:31:49.679+0200 [DEBUG] module.kube-hetzner.hcloud_load_balancer_network.cluster[0]: applying the planned Create change
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: --- Request:
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: POST /v1/load_balancers/1493234/actions/attach_to_network HTTP/1.1
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Host: api.hetzner.cloud
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: User-Agent: hcloud-terraform/1.51.0 hcloud-go/2.21.0
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Content-Length: 19
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Authorization: REDACTED
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Content-Type: application/json
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Accept-Encoding: gzip
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: {"network":3061816}
2025-06-10T13:31:49.683+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.684+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-06-10T13:31:49.686+0200 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/random/3.7.2/linux_amd64/terraform-provider-random_v3.7.2_x5 id=66041
2025-06-10T13:31:49.686+0200 [DEBUG] provider: plugin exited
2025-06-10T13:31:49.686+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-06-10T13:31:49.688+0200 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/cloudinit/2.3.7/linux_amd64/terraform-provider-cloudinit_v2.3.7_x5 id=66095
2025-06-10T13:31:49.688+0200 [DEBUG] provider: plugin exited
2025-06-10T13:31:49.692+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-06-10T13:31:49.693+0200 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/tenstad/remote/0.2.0/linux_amd64/terraform-provider-remote_v0.2.0 id=66078
2025-06-10T13:31:49.694+0200 [DEBUG] provider: plugin exited
2025-06-10T13:31:49.694+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-06-10T13:31:49.695+0200 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/null/3.2.4/linux_amd64/terraform-provider-null_v3.2.4_x5 id=66050
2025-06-10T13:31:49.695+0200 [DEBUG] provider: plugin exited
2025-06-10T13:31:49.695+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-06-10T13:31:49.696+0200 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/local/2.5.3/linux_amd64/terraform-provider-local_v2.5.3_x5 id=66087
2025-06-10T13:31:49.696+0200 [DEBUG] provider: plugin exited
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: --- Response:
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: HTTP/2.0 422 Unprocessable Entity
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Content-Length: 164
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Access-Control-Allow-Headers: X-Requested-With,Authorization,Content-Type
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,PATCH,DELETE
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Access-Control-Allow-Origin: *
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Access-Control-Expose-Headers: Link,X-Correlation-ID
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Access-Control-Max-Age: 86400
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Content-Type: application/json
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Date: Tue, 10 Jun 2025 11:31:49 GMT
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Ratelimit-Limit: 3600
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Ratelimit-Remaining: 3557
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Ratelimit-Reset: 1749555152
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Strict-Transport-Security: max-age=31536000; includeSubDomains
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Traceparent: 00-7031a2240f43f32358edc09c6cd48795-03fd5263114367a2-01
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Uber-Trace-Id: 7031a2240f43f32358edc09c6cd48795:03fd5263114367a2:0:1
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: X-Correlation-Id: 7031a2240f43f32358edc09c6cd48795
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: {
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0:     "error": {
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0:         "code": "load_balancer_already_attached",
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0:         "message": "load balancer already attached to a network",
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0:         "details": null
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0:     }
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: }
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: --- Request:
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: GET /v1/load_balancers/1493234 HTTP/1.1
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Host: api.hetzner.cloud
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: User-Agent: hcloud-terraform/1.51.0 hcloud-go/2.21.0
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Authorization: REDACTED
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0: Accept-Encoding: gzip
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
2025-06-10T13:31:49.966+0200 [DEBUG] provider.terraform-provider-hcloud_v1.51.0
```

**Comment by ulfgebhardt** [comment]
I have the same behaviour. The problem persists, no manual configuration, no autoscaling. How do I fix this error? tested with the latest version 2.17.3.
